globalProperties:
    apiDocs: false
    apiTests: false
    modelDocs: false
    modelTests: false

additionalProperties:
    withInterfaces: true
    useSingleRequestParameter: true

nameMappings:
  xFields: fields
  X-Flatten: flatten
  X-Languages: languages
  X-NoSlowTotal: noSlowTotal
  X-NoTotal: noTotal
  X-Unpublished: unpublished
